#!/command/with-contenv sh

set -euo pipefail
export BF_E="${PWD##*/}/$(basename ${0})"


#======================================================================================================================
# Run Lighttpd server.
#======================================================================================================================

[[ ! -f ${LIGHTTPD_CONF} ]] && bf-error "Lighttpd configuration file not found."

bf-echo "Starting Lighttpd."
lighttpd -f ${LIGHTTPD_CONF}
